### PR TITLE
Z-Stack 3.x.0 20210708

### PR DESCRIPTION
**Pull request by Koenkk**

### CODE REVIEW

**Comment by kevincaradant** [comment]
Hi

I'm a little bit lost with these comments, should I wait an update of the herdsman before to update ? 

I'm currently working on the 20201130 version.

Is it worth to update it or it will be useless ? 

Thank you

**Comment by Koenkk** [comment]
This firmware can be used with any z2m version, generally firmware changes are relatively small and there is not much reason to update if you don't have any issues currently.

**Comment by kevincaradant** [comment]
Alright thank you for the explanation :)

> "here is not much reason to update if you don't have any issues currently."
    I have some troubles since few days but as I use the same version of firmware (20201130) since 10 months, I don't think that the firmware is responsible of my problem mentioned here (cf: https://github.com/Koenkk/zigbee2mqtt/issues/8460)

**Comment by untergeek** [comment]
I know this is late, but is there a reason only the Coordinator firmware was built for the CC2652R? 

I have the TI LAUNCHXL-CC26xR1, and have been using the Router firmware, but noticed that it [hasn't been updated since 2021-01-28](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/Z-Stack_3.x.0/bin).

**Comment by knubb** [comment]
I tried downloading but the ZIP is empty? Could you help?

**Comment by arteck** [comment]
download comlete project not only the zip file

**Pull request merged**
