### PR TITLE
Manually patched, built and tested  for CC1352R1

### PR DESCRIPTION
**Pull request by psychogenic**
Hi,  

Only had the CC1352R1 Launchpad (https://www.ti.com/tool/LAUNCHXL-CC1352R1) around to play with, so I manually went through the firmware patch and did the job on the znp_CC1352R1_LAUNCHXL_tirtos_ccs project.

After config, got home assistant connected to the z-stack and added some zigbee devices through it without issue.

Don't know if this can be useful to others, but it's another supported devkit.  Stuck patch file and pre-built hex in a CC1352R1_LAUNCHXL branch.

CC1352R1HA

### CODE REVIEW

**Comment by Koenkk** [comment]
Besides the dev board, is this chip also used in other devices?

**Comment by psychogenic** [comment]
Hi,

Well, it's the classic CC1352R (https://www.ti.com/product/CC1352R) as used in the sensor tags (https://www.ti.com/tool/LPSTK-CC1352R), a custom device I'm building and I assume many other things, though I don't actually know...

I attempted ramming the existing 1352P2 firmware onto this board to no avail, hence the integration with the R1 launchpad dev kit.

**Comment by Koenkk** [comment]
I see, since this is not a very common device I tend to not support it for now. Reason is that this adds additional maintenance for me when providing new fws. There are many exotic variants (e.g. https://www.ti.com/product/CC2652P7) and I want to focus on the ones widely available.

**Comment by psychogenic** [comment]
Ok, cool.  I'll leave my fork up for the lonely few like me :)

**Comment by psychogenic** [comment]
Works for me, thanks!

**Comment by Koenkk** [comment]
Could you make a PR? (I assume the pins are the same as the other dev boards)

**Comment by Koenkk** [comment]
> to update the readme

Yes to update just the readme.

**Pull request closed without merging**
