### PR TITLE
Add firmware for CC2538-CC2592 based USB stick by MODKAM.RU

### PR DESCRIPTION
**Pull request by reverieline**
MODKAMRU V3 is an open source USB board based on CC2538-CC2592 module.
https://modkam.ru/?p=1112

The firmware is built on TI Z-Stack 3.0.2 with minimal changes. 
Tuning and testing is still a work in progress.

### CODE REVIEW

**Comment by Koenkk** [comment]
Could you also provide the corresponding instructions to reproduce the firmware? (like https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.0.x/COMPILE.md)

**Comment by Koenkk** [comment]
Note to self; after this merge: https://github.com/Koenkk/zigbee2mqtt.io/pull/208

**Comment by Koenkk** [comment]
Thanks!

**Comment by reverieline** [comment]
> 
> 
> Thanks!

Thank you!

**Comment by Gamester17** [comment]
Does the README.md for Z-Stack-firmware coordinator firmware also need to be updated for now that #144 have been merged adding support for CC2538 + CC2592 module?

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/README.md

**Comment by Gamester17** [comment]
@reverieline submitted PR for an update for README.md to also list Z-Stack 3.0.x on CC2538 in https://github.com/Koenkk/Z-Stack-firmware/pull/149

**Pull request merged**
