### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by guozi7788**
Update SONOFF Zigbee 3.0 USB Dongle Plus hardware information

### CODE REVIEW

**Comment by Hedda** [comment]
@guozi7788 Do you also happen have any more information on DIO for 2.4GHz switching as used in "RF Switch Control Pins"? 

Does maybe DIO_5, DIO_6 or DIO_28 switch to 2.4GHz if it is DIO_29 thaT swiches to 2.4GHz 20dBm?

I added the info on "DIO_29: 20dBm PA" pin for PA in https://github.com/Koenkk/Z-Stack-firmware/pull/325

But that information came from @chiakikato who checked RF traces for PA and as I understand he could not find a DIO connected for RF switch to or 2.4GHz 5dBm and 2.4GHz 20dBm switching?

Please see whole discusson in the other thread and maybe give feedback there to clear up questions:

https://github.com/Koenkk/zigbee2mqtt/discussions/8840

Again, my PR was just based on posts with observation comments by @chiakikato

_Originally posted by @chiakikato in https://github.com/Koenkk/zigbee2mqtt/discussions/8840#discussioncomment-1550021_

> I check the trace of SONOFF.
> DIO_29: 20dBm PA is connected. but DIO_28: is N.C.
>it uses PE4259 or compatible's SC-70 6P RF switch which does not have 3 RF signals input for 2.4GHz 5dBm, 2.4GHz 20dBm and SubGHz.  
>I think it is a reason DIO_28 is not connected.

_Originally posted by @chiakikato in https://github.com/Koenkk/zigbee2mqtt/discussions/8840#discussioncomment-1550148_

> I set RF switch control as HIGH by external hardwired method and got -22~-19dBm worth result.
> It means the firmware's RF switch control has no problem.
> SONOFF RF antenna and/or RF circuit need to be doubted.  

PS: Please compare "RF Switch Control Pins"colum for the different CC2652P and CC1352P based adapters, and note that that there are also questions in regards to "BSL Trigger Pin" and "Auto-BSL" as well so if possible please also fill in the info there too:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md

<table>
<thead>
  <tr>
    <th>Adapter</th>
    <th>TI Chip/Module Used</th>
    <th>Firmware to Flash</th>
    <th>BSL Trigger Pin (1)</th>
    <th>Auto-BSL (2)</th>
    <th>RF Switch Control Pins (3)</th>
    <th>LED(s)</th>
    <th>Hardware Flow Control</th>
  </tr>
</thead>
<tbody>
    <tr>
    <td>TI LAUNCHXL-CC1352P-2</td>
    <td>CC1352P</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA<br>DIO_30: Sub-1GHz</td>
    <td>DIO_6 (Red)<br>DIO_7 (Green)<br></td>
    <td>?</td>
  </tr>
<tr>
    <td>Electrolama zzhp-lite</td>
    <td>CC2652P<br>(Ebyte E72)<br></td>
    <td>CC1352P2_CC2652P_other_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_5: 20dBm PA ??<br>DIO_6: 2.4GHz ??<br></td>
    <td>DIO_7 (Pink)</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Electrolama zzhp</td>
    <td>CC2652P</td>
    <td>CC1352P2_CC2652P_other_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_5: 20dBm PA ??<br>DIO_6: 2.4GHz ??</td>
    <td>DIO_7 (Pink)</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Electrolama zoe2</td>
    <td>CC1352P<br>(Ebyte E79)<br></td>
    <td>CC1352P2_CC2652P_other_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_5: 20dBm PA ??<br>DIO_6: 2.4GHz ??</td>
    <td>DIO_7 (Pink)</td>
    <td>?</td>
  </tr>
<tr>
    <td><a href="https://zig-star.com">ZigStar Stick v4</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Only for CH340C ver.</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_6 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>CircuitSetup.us Zigbee Stick</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2 PCB Ant.)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_6 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's CC2652P2 USB Coordinator<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's Zigbee Gateways (CC2652P2 variant)<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Tube's Zigbee PoE (Power Over Ethernet) Serial Coordinator (CC2652P2 variant)<br></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>N/A</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>N/A</td>
    <td>?</td>
  </tr>
  <tr>
    <td>Egony Stick V4<br>(Ebyte ver.)</td>
    <td>CC2652P<br>(Ebyte E72-2G4M20S1E)</td>
    <td>CC1352P2_CC2652P_other_*.zip</td>
    <td>DIO_15</td>
    <td>Yes<br>(from Rev.2.0)</td>
    <td>DIO_5: 20dBm PA<br>DIO_6: 2.4GHz</td>
    <td>DIO_8 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>Egony Stick V4<br>(RFSTAR ver.)</td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>cod.m Zigbee CC2652P RPi Module</td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2)</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>Yes</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>Gio-dot Z-Bee Duo with CC2652P</td>
    <td>CC2652P<br>(Ebyte E72-2G4M20S1E)</td>
    <td>CC1352P2_CC2652P_other_*.zip</td>
    <td>DIO_15</td>
    <td>Yes<br>(from Rev.2.0)</td>
    <td>DIO_5: 20dBm PA<br>DIO_6: 2.4GHz</td>
    <td>DIO_8 (Green)<br>DIO_7 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>cyijun <a href="https://github.com/cyijun/OpenZ3Gateway">OpenZ3Gateway</a></td>
    <td>CC2652P<br>(RFSTAR RF-BM-2652P2 SMA Ant.)<br></td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>DIO_15</td>
    <td>No</td>
    <td>DIO_28: 2.4Ghz<br>DIO_29: 20dBm PA</td>
    <td>DIO_7 (Green)<br>DIO_6 (Red)<br></td>
    <td>?</td>
  </tr>
  <tr>
    <td>SONOFF Zigbee 3.0 USB Dongle Plus by ITead</td>
    <td>CC2652P</td>
    <td>CC1352P2_CC2652P_launchpad_*.zip</td>
    <td>?</td>
    <td>?</td>
    <td>DIO_29: 20dBm PA</td>
    <td>?</td>
    <td>DIO13: TX<br>DIO12:RC<br>DIO19: CTS<br>DIO18: RTS</td>
  </tr>
</tbody>
</table>

**Comment by guozi7788** [comment]
@Hedda As you said, PE4259 is used on the dongle, The Pin6 is connected to Vdd, and Pin4 is connected to DIO29. Therefore, it only uses DIO29 to control the switching between 5dBm (PE4259’s RF2) and 20dBm (PE4259’s RF1).

The RF has been tested by the instrument and the result is normal.
I am not sure if the abnormality you mentioned is caused by individual differences. I will report your question to the relevant personnel.

I have added the information you expect to know in this PR:
BSL Trigger Pin: DIO15
Auto-BSL: yes
LED: DIO_7(Not welded) Power LED(Red)
Hardware Flow Control: DIO13: TX DIO12: RC DIO19: CTS(Need DIP-switch ON) DIO18: RTS(Need DIP-switch ON)

You can update the relevant Thread. If you expect me to update, please let me know.

Thanks.

**Comment by Hedda** [comment]
@guozi7788 Are you employed by ITead/Sonoff as an engineer and have specifically worked on this specific product for them?

> I have added the information you expect to know in this PR:
> BSL Trigger Pin: DIO15
> **Auto-BSL: yes**
> LED: DIO_7(Not welded) Power LED(Red)
> Hardware Flow Control: DIO13: TX DIO12: RC DIO19: CTS(Need DIP-switch ON) DIO18: RTS(Need DIP-switch ON)

FYI, It does not look like "**_Auto-BSL = Yes_**" made it into this pull request by yourself, however, is in this other PR -> https://github.com/Koenkk/Z-Stack-firmware/pull/328

**Comment by Hedda** [comment]
Bump and not stale, just waiting for review.

**Pull request merged**
