### PR TITLE
Add new max_devices alternative

### PR DESCRIPTION
**Pull request by glentakahashi**
Opening based on conversation here https://github.com/Koenkk/Z-Stack-firmware/issues/10#issuecomment-423723585

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks for the PR!

I just updated the instructions for the optimized firmware which also includes the `XDATA` change. https://github.com/Koenkk/Z-Stack-firmware/tree/optimize/coordinator/CC2531.

I think all the instructions are the same except the *Defined symbols*. Could you post the complete list that you used for this firmware?

**Comment by glentakahashi** [comment]
@Koenkk , perfect. Since you added XDATA to the original instructions, I've changed the readme here to be more concise. For context, I used exactly the same symbols as you had in your original version except changing the two related to devices + routers.

**Comment by Koenkk** [comment]
Great, thanks!

**Comment by Koenkk** [comment]
Did you change anything else? With `XDATA` set to `0x300` and the following symbols:

```
CC2531ZNP
ASSERT_RESET
FAKE_CRC_SHDW
TC_LINKKEY_JOIN
SECURE=1
NWK_MAX_DEVICE_LIST=44
MAXMEMHEAP=3199
INTER_PAN
INCLUDE_REVISION_INFORMATION
CONCENTRATOR_ENABLE=1
CONCENTRATOR_DISCOVERY_TIME=120
MAX_RTG_SRC_ENTRIES=12
SRC_RTG_EXPIRY_TIME=2
CONCENTRATOR_ROUTE_CACHE=1
MTO_RREQ_LIMIT_TIME=5000
LINK_DOWN_TRIGGER=5
NWK_ROUTE_AGE_LIMIT=10
BCAST_DELIVERY_TIME=100
DEF_NWK_RADIUS=5
NWK_ROUTE_AGE_LIMIT=15
DEFAULT_ROUTE_REQUEST_RADIUS=15
ROUTE_DISCOVERY_TIME=10
ZDNWKMGR_MIN_TRANSMISSIONS=0
NWK_LINK_STATUS_PERIOD=23
MAX_NEIGHBOR_ENTRIES=1
``` 

I can't compile it, error:

```
Error[e104]: Failed to fit all segments into specified ranges. Problem discovered in segment XDATA_N. Unable to place 2 block(s) (0x200 byte(s) total) in 0x1f7 byte(s) of memory. The  
problem occurred while processing the segment placement command "-P(XDATA)XDATA_N=_XDATA_START-_XDATA_END", where at the moment of placement the available  
memory ranges were "XDATA:1d09-1eff" 
```

**Comment by glentakahashi** [comment]
Ohhh, I just realized I'm missing the MAXMEMHEAP=3199 line in my build as well as the other CONCENTRATOR_ENABLE downwards. I built my version before your revamped instructions 2 days ago. Also my timed trial ran out so I unfortunately can no longer rebuild the project to test the new settings.

With MAXMEMHEAP=3199 what is the max number of devices you can get to build?

**Comment by Koenkk** [comment]
I used the following defines for now:

``` 
+  #define CC2531ZNP
+  #define ASSERT_RESET
+  #define FAKE_CRC_SHDW
+  #define TC_LINKKEY_JOIN
+  #define SECURE 1
+  #define NWK_MAX_DEVICE_LIST 43
+  #define MAXMEMHEAP 3199
+  #define INTER_PAN 1
+  #define INCLUDE_REVISION_INFORMATION
+  #define MAX_NEIGHBOR_ENTRIES 1
```

**Comment by glentakahashi** [comment]
Cool! 43 devices is still great

**Comment by boucz** [comment]
maybe another option could be interresting, like ~30 devices and ~5 routers supported ?

**Pull request merged**
