### PR TITLE
support for CC2652R7 

### PR DESCRIPTION
**Pull request by Sheng2216**
We manually port the changes for the CC2652R chip on the patch file to the CC2652R7 without changing anything. We tested it on the TI CC2652R7 development kit and also our company's prototype board based on the CC2652R7 chip, and we are happy to report that the firmware works smoothly and without any issues.

To make things more convenient for you, we have packed the changes for the CC2652R7 into a single patch and uploaded the `.hex `file to the bin directory. You can find more details on the GitHub page at https://github.com/RAKWireless/CC2652R7_firmware.

We hope that you find our contribution useful.

### CODE REVIEW

**Comment by Koenkk** [comment]
I've published a CC1352P7 firmware, could you check if it works on the CC2652P7? (as CC1352P2 and CC2652P2 also share the same fw)

**Comment by Koenkk** [comment]
> Do you see the extra flash & ram giving any benefits?

With the additional flash more Zigbee 3.0 devices can join the network (200 vs 300). RAM is indeed bigger, not sure if this will bring benefits but it is expected.

**Comment by Koenkk** [comment]
> Do you see the extra flash & ram giving any benefits?

With the additional flash more Zigbee 3.0 devices can join the network (200 vs 300). RAM is indeed bigger, not sure if this will bring benefits but it is expected.

**Comment by Koenkk** [comment]
> Do you see the extra flash & ram giving any benefits?

With the additional flash more Zigbee 3.0 devices can join the network (200 vs 300). RAM is indeed bigger, not sure if this will bring benefits but it is expected.

**Comment by Sheng2216** [comment]
> Pretty sure this guy as me only has the R7 devkit, not P7.

yup, we don't have the P7

**Comment by Koenkk** [comment]
@Sheng2216 does your company plan to release a CC2652R7 based adapter?

**Comment by Koenkk** [comment]
I've published a firmware, @Sheng2216 could you check if it works? https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/bin/CC2652R7_coordinator_20230507.zip

**Comment by io53** [comment]
> I've published a firmware, @Sheng2216 could you check if it works? https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/bin/CC2652R7_coordinator_20230507.zip

I flashed it and it works for me 👍

**Comment by Sheng2216** [comment]
> I've published a firmware, @Sheng2216 could you check if it works? https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/bin/CC2652R7_coordinator_20230507.zip
it works like a charm

**Comment by Koenkk** [comment]
Great! Then I will close this.

**Pull request closed without merging**
