### PR TITLE
boyscout: QoL improvements

### PR DESCRIPTION
**Pull request by oliv3r**
* Split maclib binary patch
* Ensure line-endings stay as intended in patch files

### CODE REVIEW

**Comment by Koenkk** [comment]
I think we should keep the CSS version as close a possible to the recommended one for this SDK. E.g. for this one it's [CCS-12.5.0](https://software-dl.ti.com/simplelink/esd/simplelink_cc13xx_cc26xx_sdk/7.41.00.17/exports/release_notes_simplelink_cc13xx_cc26xx_sdk_7_41_00_17.html)

**Comment by oliv3r** [comment]
So I've downgraded CSS as per desire to match the SDK, which I kind of agree with.

**Comment by agriadsi** [comment]
The firmware.patch file included with 20240710 release requires, that manipulation with projects (at least znp_CC1352P_2_LAUNCHXL_tirtos7_ticlang/znp.syscfg), are made with SysConfig 1.19.0 (look at line 187747 of firmware.patch: @versions {"tool":"1.19.0+3426"}). The required SysConfig version is not a standard part of CCS 12.6, neither 12.8.
So, I had to take additional steps to apply the patch:
1. Download and install SysConfig 1.19.0.
2. Attach new SysConfig to CCS.
3. Replace SysConfig for all projects.
Then do all other steps from COMPILE.md

Otherwise, the patch didn't apply.
The splitted version from this PR has the same requirement (line 1756).

@Koenkk If the version of SysConfig 1.19.0 is not necessary for firmware build, maybe it's better to make a new version of firmware.patch without this requirement?

BTW CCS 12.8 and 12.6 produces the same result, firmware hex files are byte-to-byte equal.
The only annoying thing is that firmware hex files build by me (CCS 12.6 on old x64 PC with Windows 11) is smaller, than built by @Koenkk.  But it works for 3+ days as for now.

**Comment by oliv3r** [comment]
I was using latest-everything and it seemed fine, but Lets go with 12.6 as koenkk suggested for this release. The next TI dump will probably go to a newer version anyway :) and after my patches, this won't be an issue at all (from a patching point of view).

**Comment by oliv3r** [comment]
Done; it's now staying with12.6

**Comment by Koenkk** [comment]
> `COMPILE.md` has to updated to accommodate for the `maclib_binary.patch`

I think this is still missing?

**Comment by oliv3r** [comment]
Ah, I thought @Koenkk had to update something there. Not sure what I would need to do with regards to the maclib patches then?

**Comment by Koenkk** [comment]
I think it should be added to step 7 of https://github.com/oliv3r/Z-Stack-firmware/blob/update_ccs/coordinator/Z-Stack_3.x.0/COMPILE.md#compiling

**Comment by oliv3r** [comment]
And now I understand what you mean; you are absolutely correct. This was lost during rebasing at some point surely. I'll fix the instruction for this commit!

**Comment by Koenkk** [comment]
Thanks!

**Comment by oliv3r** [comment]
Thanks for the merge, i'll rebase the other mr's and we can focus on those next. Also I bought a second sonoff stick ;)

**Pull request merged**
